In [140]:
import numpy as np 
import pandas as pd 
import re

In [141]:
data = pd.read_csv("/home/saaho/Mechine_learnig/Dataset/IPL/match_summary.csv")

In [142]:
data

IPL Edition        Date     Time  \
0            2023  2023-03-31  7:30 PM   
1            2023  2023-04-01  3:30 PM   
2            2023  2023-04-01  7:30 PM   
3            2023  2023-04-02  3:30 PM   
4            2023  2023-04-02  7:30 PM   
...           ...         ...      ...   
1032         2008  2008-05-28  4:00 PM   
1033         2008  2008-05-28  8:00 PM   
1034         2008  2008-05-30  8:00 PM   
1035         2008  2008-05-31  8:00 PM   
1036         2008  2008-06-01  8:15 PM   

                                          Match Details  \
0      GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match   
1      PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match   
2     LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match   
3     SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...   
4     ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...   
...                                                 ...   
1032  ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...   
1033       PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match   
1034  DELHI CAPITALS vs RAJASTHAN ROYALS, 1st Semi-F...   
1035  CHENNAI SUPER KINGS vs PUNJAB KINGS, 2nd Semi-...   
1036     CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final   

                           Team 1                 Team 2  \
0                  GUJARAT TITANS    CHENNAI SUPER KINGS   
1                    PUNJAB KINGS  KOLKATA KNIGHT RIDERS   
2            LUCKNOW SUPER GIANTS         DELHI CAPITALS   
3             SUNRISERS HYDERABAD       RAJASTHAN ROYALS   
4     ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
...                           ...                    ...   
1032  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
1033                 PUNJAB KINGS       RAJASTHAN ROYALS   
1034               DELHI CAPITALS       RAJASTHAN ROYALS   
1035          CHENNAI SUPER KINGS           PUNJAB KINGS   
1036          CHENNAI SUPER KINGS       RAJASTHAN ROYALS   

                            Winner  \
0                  Gujarat Titans    
1                    Punjab Kings    
2            Lucknow Super Giants    
3                Rajasthan Royals    
4     Royal Challengers Bangalore    
...                            ...   
1032               Mumbai Indians    
1033              Kings XI Punjab    
1034             Rajasthan Royals    
1035          Chennai Super Kings    
1036             Rajasthan Royals    

                                        Winning Details  
0                          Gujarat Titans won by 5 wkts  
1               Punjab Kings won by 7 runs (DLS method)  
2                   Lucknow Super Giants won by 50 runs  
3                       Rajasthan Royals won by 72 runs  
4             Royal Challengers Bangalore won by 8 wkts  
...                                                 ...  
1032  Mumbai Indians won by 9 wickets (with 12 balls...  
1033                     Kings XI Punjab won by 41 runs  
1034                   Rajasthan Royals won by 105 runs  
1035  Chennai Super Kings won by 9 wickets (with 31 ...  
1036  Rajasthan Royals won by 3 wickets (with 0 ball...  

[1037 rows x 8 columns]

In [143]:
data.drop(["Time","Date"], axis=1 , inplace=True)

In [144]:
data

IPL Edition                                      Match Details  \
0            2023   GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match   
1            2023   PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match   
2            2023  LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match   
3            2023  SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...   
4            2023  ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...   
...           ...                                                ...   
1032         2008  ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...   
1033         2008       PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match   
1034         2008  DELHI CAPITALS vs RAJASTHAN ROYALS, 1st Semi-F...   
1035         2008  CHENNAI SUPER KINGS vs PUNJAB KINGS, 2nd Semi-...   
1036         2008     CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final   

                           Team 1                 Team 2  \
0                  GUJARAT TITANS    CHENNAI SUPER KINGS   
1                    PUNJAB KINGS  KOLKATA KNIGHT RIDERS   
2            LUCKNOW SUPER GIANTS         DELHI CAPITALS   
3             SUNRISERS HYDERABAD       RAJASTHAN ROYALS   
4     ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
...                           ...                    ...   
1032  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
1033                 PUNJAB KINGS       RAJASTHAN ROYALS   
1034               DELHI CAPITALS       RAJASTHAN ROYALS   
1035          CHENNAI SUPER KINGS           PUNJAB KINGS   
1036          CHENNAI SUPER KINGS       RAJASTHAN ROYALS   

                            Winner  \
0                  Gujarat Titans    
1                    Punjab Kings    
2            Lucknow Super Giants    
3                Rajasthan Royals    
4     Royal Challengers Bangalore    
...                            ...   
1032               Mumbai Indians    
1033              Kings XI Punjab    
1034             Rajasthan Royals    
1035          Chennai Super Kings    
1036             Rajasthan Royals    

                                        Winning Details  
0                          Gujarat Titans won by 5 wkts  
1               Punjab Kings won by 7 runs (DLS method)  
2                   Lucknow Super Giants won by 50 runs  
3                       Rajasthan Royals won by 72 runs  
4             Royal Challengers Bangalore won by 8 wkts  
...                                                 ...  
1032  Mumbai Indians won by 9 wickets (with 12 balls...  
1033                     Kings XI Punjab won by 41 runs  
1034                   Rajasthan Royals won by 105 runs  
1035  Chennai Super Kings won by 9 wickets (with 31 ...  
1036  Rajasthan Royals won by 3 wickets (with 0 ball...  

[1037 rows x 6 columns]

In [145]:
data.drop(['Winning Details'] ,axis=1, inplace=True)

In [146]:
data

IPL Edition                                      Match Details  \
0            2023   GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match   
1            2023   PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match   
2            2023  LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match   
3            2023  SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...   
4            2023  ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...   
...           ...                                                ...   
1032         2008  ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...   
1033         2008       PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match   
1034         2008  DELHI CAPITALS vs RAJASTHAN ROYALS, 1st Semi-F...   
1035         2008  CHENNAI SUPER KINGS vs PUNJAB KINGS, 2nd Semi-...   
1036         2008     CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final   

                           Team 1                 Team 2  \
0                  GUJARAT TITANS    CHENNAI SUPER KINGS   
1                    PUNJAB KINGS  KOLKATA KNIGHT RIDERS   
2            LUCKNOW SUPER GIANTS         DELHI CAPITALS   
3             SUNRISERS HYDERABAD       RAJASTHAN ROYALS   
4     ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
...                           ...                    ...   
1032  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
1033                 PUNJAB KINGS       RAJASTHAN ROYALS   
1034               DELHI CAPITALS       RAJASTHAN ROYALS   
1035          CHENNAI SUPER KINGS           PUNJAB KINGS   
1036          CHENNAI SUPER KINGS       RAJASTHAN ROYALS   

                            Winner  
0                  Gujarat Titans   
1                    Punjab Kings   
2            Lucknow Super Giants   
3                Rajasthan Royals   
4     Royal Challengers Bangalore   
...                            ...  
1032               Mumbai Indians   
1033              Kings XI Punjab   
1034             Rajasthan Royals   
1035          Chennai Super Kings   
1036             Rajasthan Royals   

[1037 rows x 5 columns]

In [147]:
mt = data["Match Details"]

In [148]:
mt

0        GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match
1        PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match
2       LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match
3       SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...
4       ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...
                              ...                        
1032    ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...
1033         PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match
1034    DELHI CAPITALS vs RAJASTHAN ROYALS, 1st Semi-F...
1035    CHENNAI SUPER KINGS vs PUNJAB KINGS, 2nd Semi-...
1036       CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final
Name: Match Details, Length: 1037, dtype: object

In [149]:
mt[1036]

'CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final'

In [150]:
pattern_semi_final = re.compile(r'Semi')
pattern_final = re.compile(r'Final')

match_details = mt.apply(lambda x: "Semi Final" if pattern_semi_final.search(x) else ("Final" if pattern_final.search(x) else x))


In [151]:
match_details

0        GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match
1        PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match
2       LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match
3       SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...
4       ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...
                              ...                        
1032    ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...
1033         PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match
1034                                           Semi Final
1035                                           Semi Final
1036                                                Final
Name: Match Details, Length: 1037, dtype: object

In [152]:
pattern_final = re.compile(r'Final')
pattern_semi_final = re.compile(r'Semi')
pattern_eliminator = re.compile(r'Eliminator')
pattern_qualifier = re.compile(r'Qualifier')

match_details = match_details.apply(lambda x: x if any(pattern.search(x) for pattern in [pattern_final, pattern_semi_final, pattern_eliminator, pattern_qualifier]) else "Leaugh Match")

In [153]:
match_details

0       Leaugh Match
1       Leaugh Match
2       Leaugh Match
3       Leaugh Match
4       Leaugh Match
            ...     
1032    Leaugh Match
1033    Leaugh Match
1034      Semi Final
1035      Semi Final
1036           Final
Name: Match Details, Length: 1037, dtype: object

In [154]:
match_details[72]

'GUJARAT TITANS vs MUMBAI INDIANS, Qualifier 2'

In [155]:
pattern_semi_final = re.compile(r'Qualifier 2')
pattern_final = re.compile(r'Qualifier 1')

match_details = match_details.apply(lambda x: "Qualifier 2" if pattern_semi_final.search(x) else ("Qualifier 1" if pattern_final.search(x) else x))

In [156]:
match_details

0       Leaugh Match
1       Leaugh Match
2       Leaugh Match
3       Leaugh Match
4       Leaugh Match
            ...     
1032    Leaugh Match
1033    Leaugh Match
1034      Semi Final
1035      Semi Final
1036           Final
Name: Match Details, Length: 1037, dtype: object

In [157]:
match_details[72]

'Qualifier 2'

In [158]:
pattern_final = re.compile(r'Final')
pattern_semi_final = re.compile(r'Semi')
pattern_eliminator = re.compile(r'Leaugh Match')
pattern_qualifier = re.compile(r'Qualifier')

match_detail = match_details.apply(lambda x: x if any(pattern.search(x) for pattern in [pattern_final, pattern_semi_final, pattern_eliminator, pattern_qualifier]) else "Eliminator")

In [159]:
match_detail
# Filter rows containing "Eliminator"
eliminator_rows = match_detail[match_details.str.contains("Eliminator")]

In [160]:
eliminator_rows

71     Eliminator
146    Eliminator
208    Eliminator
270    Eliminator
330    Eliminator
390    Eliminator
450    Eliminator
510    Eliminator
570    Eliminator
630    Eliminator
706    Eliminator
782    Eliminator
856    Eliminator
Name: Match Details, dtype: object

In [161]:
match_detail

0       Leaugh Match
1       Leaugh Match
2       Leaugh Match
3       Leaugh Match
4       Leaugh Match
            ...     
1032    Leaugh Match
1033    Leaugh Match
1034      Semi Final
1035      Semi Final
1036           Final
Name: Match Details, Length: 1037, dtype: object

In [162]:
new_data = data

In [163]:
new_data

IPL Edition                                      Match Details  \
0            2023   GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match   
1            2023   PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match   
2            2023  LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match   
3            2023  SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...   
4            2023  ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...   
...           ...                                                ...   
1032         2008  ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...   
1033         2008       PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match   
1034         2008  DELHI CAPITALS vs RAJASTHAN ROYALS, 1st Semi-F...   
1035         2008  CHENNAI SUPER KINGS vs PUNJAB KINGS, 2nd Semi-...   
1036         2008     CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final   

                           Team 1                 Team 2  \
0                  GUJARAT TITANS    CHENNAI SUPER KINGS   
1                    PUNJAB KINGS  KOLKATA KNIGHT RIDERS   
2            LUCKNOW SUPER GIANTS         DELHI CAPITALS   
3             SUNRISERS HYDERABAD       RAJASTHAN ROYALS   
4     ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
...                           ...                    ...   
1032  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
1033                 PUNJAB KINGS       RAJASTHAN ROYALS   
1034               DELHI CAPITALS       RAJASTHAN ROYALS   
1035          CHENNAI SUPER KINGS           PUNJAB KINGS   
1036          CHENNAI SUPER KINGS       RAJASTHAN ROYALS   

                            Winner  
0                  Gujarat Titans   
1                    Punjab Kings   
2            Lucknow Super Giants   
3                Rajasthan Royals   
4     Royal Challengers Bangalore   
...                            ...  
1032               Mumbai Indians   
1033              Kings XI Punjab   
1034             Rajasthan Royals   
1035          Chennai Super Kings   
1036             Rajasthan Royals   

[1037 rows x 5 columns]

In [164]:
other_data = new_data.drop(columns=["Match Details"] ,axis=1)

In [165]:
other_data

IPL Edition                       Team 1                 Team 2  \
0            2023               GUJARAT TITANS    CHENNAI SUPER KINGS   
1            2023                 PUNJAB KINGS  KOLKATA KNIGHT RIDERS   
2            2023         LUCKNOW SUPER GIANTS         DELHI CAPITALS   
3            2023          SUNRISERS HYDERABAD       RAJASTHAN ROYALS   
4            2023  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
...           ...                          ...                    ...   
1032         2008  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
1033         2008                 PUNJAB KINGS       RAJASTHAN ROYALS   
1034         2008               DELHI CAPITALS       RAJASTHAN ROYALS   
1035         2008          CHENNAI SUPER KINGS           PUNJAB KINGS   
1036         2008          CHENNAI SUPER KINGS       RAJASTHAN ROYALS   

                            Winner  
0                  Gujarat Titans   
1                    Punjab Kings   
2            Lucknow Super Giants   
3                Rajasthan Royals   
4     Royal Challengers Bangalore   
...                            ...  
1032               Mumbai Indians   
1033              Kings XI Punjab   
1034             Rajasthan Royals   
1035          Chennai Super Kings   
1036             Rajasthan Royals   

[1037 rows x 4 columns]

In [166]:
new_data = pd.concat([data,match_detail],axis=1)

In [167]:
new_data

IPL Edition                                      Match Details  \
0            2023   GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match   
1            2023   PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match   
2            2023  LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match   
3            2023  SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...   
4            2023  ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...   
...           ...                                                ...   
1032         2008  ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...   
1033         2008       PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match   
1034         2008  DELHI CAPITALS vs RAJASTHAN ROYALS, 1st Semi-F...   
1035         2008  CHENNAI SUPER KINGS vs PUNJAB KINGS, 2nd Semi-...   
1036         2008     CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final   

                           Team 1                 Team 2  \
0                  GUJARAT TITANS    CHENNAI SUPER KINGS   
1                    PUNJAB KINGS  KOLKATA KNIGHT RIDERS   
2            LUCKNOW SUPER GIANTS         DELHI CAPITALS   
3             SUNRISERS HYDERABAD       RAJASTHAN ROYALS   
4     ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
...                           ...                    ...   
1032  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
1033                 PUNJAB KINGS       RAJASTHAN ROYALS   
1034               DELHI CAPITALS       RAJASTHAN ROYALS   
1035          CHENNAI SUPER KINGS           PUNJAB KINGS   
1036          CHENNAI SUPER KINGS       RAJASTHAN ROYALS   

                            Winner Match Details  
0                  Gujarat Titans   Leaugh Match  
1                    Punjab Kings   Leaugh Match  
2            Lucknow Super Giants   Leaugh Match  
3                Rajasthan Royals   Leaugh Match  
4     Royal Challengers Bangalore   Leaugh Match  
...                            ...           ...  
1032               Mumbai Indians   Leaugh Match  
1033              Kings XI Punjab   Leaugh Match  
1034             Rajasthan Royals     Semi Final  
1035          Chennai Super Kings     Semi Final  
1036             Rajasthan Royals          Final  

[1037 rows x 6 columns]

In [168]:
other_data

IPL Edition                       Team 1                 Team 2  \
0            2023               GUJARAT TITANS    CHENNAI SUPER KINGS   
1            2023                 PUNJAB KINGS  KOLKATA KNIGHT RIDERS   
2            2023         LUCKNOW SUPER GIANTS         DELHI CAPITALS   
3            2023          SUNRISERS HYDERABAD       RAJASTHAN ROYALS   
4            2023  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
...           ...                          ...                    ...   
1032         2008  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
1033         2008                 PUNJAB KINGS       RAJASTHAN ROYALS   
1034         2008               DELHI CAPITALS       RAJASTHAN ROYALS   
1035         2008          CHENNAI SUPER KINGS           PUNJAB KINGS   
1036         2008          CHENNAI SUPER KINGS       RAJASTHAN ROYALS   

                            Winner  
0                  Gujarat Titans   
1                    Punjab Kings   
2            Lucknow Super Giants   
3                Rajasthan Royals   
4     Royal Challengers Bangalore   
...                            ...  
1032               Mumbai Indians   
1033              Kings XI Punjab   
1034             Rajasthan Royals   
1035          Chennai Super Kings   
1036             Rajasthan Royals   

[1037 rows x 4 columns]

In [169]:
new_data = pd.concat([other_data,match_detail],axis=1)

In [170]:
new_data

IPL Edition                       Team 1                 Team 2  \
0            2023               GUJARAT TITANS    CHENNAI SUPER KINGS   
1            2023                 PUNJAB KINGS  KOLKATA KNIGHT RIDERS   
2            2023         LUCKNOW SUPER GIANTS         DELHI CAPITALS   
3            2023          SUNRISERS HYDERABAD       RAJASTHAN ROYALS   
4            2023  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
...           ...                          ...                    ...   
1032         2008  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
1033         2008                 PUNJAB KINGS       RAJASTHAN ROYALS   
1034         2008               DELHI CAPITALS       RAJASTHAN ROYALS   
1035         2008          CHENNAI SUPER KINGS           PUNJAB KINGS   
1036         2008          CHENNAI SUPER KINGS       RAJASTHAN ROYALS   

                            Winner Match Details  
0                  Gujarat Titans   Leaugh Match  
1                    Punjab Kings   Leaugh Match  
2            Lucknow Super Giants   Leaugh Match  
3                Rajasthan Royals   Leaugh Match  
4     Royal Challengers Bangalore   Leaugh Match  
...                            ...           ...  
1032               Mumbai Indians   Leaugh Match  
1033              Kings XI Punjab   Leaugh Match  
1034             Rajasthan Royals     Semi Final  
1035          Chennai Super Kings     Semi Final  
1036             Rajasthan Royals          Final  

[1037 rows x 5 columns]

In [171]:
new_data["Match Details"].unique()

array(['Leaugh Match', 'Qualifier 1', 'Eliminator', 'Qualifier 2',
       'Final', 'Semi Final'], dtype=object)

In [172]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
new_data['IPL Edition'] = label_encoder.fit_transform(new_data['IPL Edition'])


In [173]:
new_data

IPL Edition                       Team 1                 Team 2  \
0              15               GUJARAT TITANS    CHENNAI SUPER KINGS   
1              15                 PUNJAB KINGS  KOLKATA KNIGHT RIDERS   
2              15         LUCKNOW SUPER GIANTS         DELHI CAPITALS   
3              15          SUNRISERS HYDERABAD       RAJASTHAN ROYALS   
4              15  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
...           ...                          ...                    ...   
1032            0  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
1033            0                 PUNJAB KINGS       RAJASTHAN ROYALS   
1034            0               DELHI CAPITALS       RAJASTHAN ROYALS   
1035            0          CHENNAI SUPER KINGS           PUNJAB KINGS   
1036            0          CHENNAI SUPER KINGS       RAJASTHAN ROYALS   

                            Winner Match Details  
0                  Gujarat Titans   Leaugh Match  
1                    Punjab Kings   Leaugh Match  
2            Lucknow Super Giants   Leaugh Match  
3                Rajasthan Royals   Leaugh Match  
4     Royal Challengers Bangalore   Leaugh Match  
...                            ...           ...  
1032               Mumbai Indians   Leaugh Match  
1033              Kings XI Punjab   Leaugh Match  
1034             Rajasthan Royals     Semi Final  
1035          Chennai Super Kings     Semi Final  
1036             Rajasthan Royals          Final  

[1037 rows x 5 columns]

In [174]:
new_data["IPL Edition"].unique()

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [175]:
new_data.drop(columns=['IPL Edition'],axis=1,inplace=True)

In [176]:
new_data

Team 1                 Team 2  \
0                  GUJARAT TITANS    CHENNAI SUPER KINGS   
1                    PUNJAB KINGS  KOLKATA KNIGHT RIDERS   
2            LUCKNOW SUPER GIANTS         DELHI CAPITALS   
3             SUNRISERS HYDERABAD       RAJASTHAN ROYALS   
4     ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
...                           ...                    ...   
1032  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
1033                 PUNJAB KINGS       RAJASTHAN ROYALS   
1034               DELHI CAPITALS       RAJASTHAN ROYALS   
1035          CHENNAI SUPER KINGS           PUNJAB KINGS   
1036          CHENNAI SUPER KINGS       RAJASTHAN ROYALS   

                            Winner Match Details  
0                  Gujarat Titans   Leaugh Match  
1                    Punjab Kings   Leaugh Match  
2            Lucknow Super Giants   Leaugh Match  
3                Rajasthan Royals   Leaugh Match  
4     Royal Challengers Bangalore   Leaugh Match  
...                            ...           ...  
1032               Mumbai Indians   Leaugh Match  
1033              Kings XI Punjab   Leaugh Match  
1034             Rajasthan Royals     Semi Final  
1035          Chennai Super Kings     Semi Final  
1036             Rajasthan Royals          Final  

[1037 rows x 4 columns]

In [177]:
Match = pd.get_dummies(new_data["Match Details"],drop_first=True)

In [178]:
Match

Final  Leaugh Match  Qualifier 1  Qualifier 2  Semi Final
0         0             1            0            0           0
1         0             1            0            0           0
2         0             1            0            0           0
3         0             1            0            0           0
4         0             1            0            0           0
...     ...           ...          ...          ...         ...
1032      0             1            0            0           0
1033      0             1            0            0           0
1034      0             0            0            0           1
1035      0             0            0            0           1
1036      1             0            0            0           0

[1037 rows x 5 columns]

In [179]:
new_data.drop(columns=["Match Details"],axis=1,inplace=True)

In [180]:
new_data = pd.concat([new_data,Match],axis=1)

In [181]:
new_data

Team 1                 Team 2  \
0                  GUJARAT TITANS    CHENNAI SUPER KINGS   
1                    PUNJAB KINGS  KOLKATA KNIGHT RIDERS   
2            LUCKNOW SUPER GIANTS         DELHI CAPITALS   
3             SUNRISERS HYDERABAD       RAJASTHAN ROYALS   
4     ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
...                           ...                    ...   
1032  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
1033                 PUNJAB KINGS       RAJASTHAN ROYALS   
1034               DELHI CAPITALS       RAJASTHAN ROYALS   
1035          CHENNAI SUPER KINGS           PUNJAB KINGS   
1036          CHENNAI SUPER KINGS       RAJASTHAN ROYALS   

                            Winner  Final  Leaugh Match  Qualifier 1  \
0                  Gujarat Titans       0             1            0   
1                    Punjab Kings       0             1            0   
2            Lucknow Super Giants       0             1            0   
3                Rajasthan Royals       0             1            0   
4     Royal Challengers Bangalore       0             1            0   
...                            ...    ...           ...          ...   
1032               Mumbai Indians       0             1            0   
1033              Kings XI Punjab       0             1            0   
1034             Rajasthan Royals       0             0            0   
1035          Chennai Super Kings       0             0            0   
1036             Rajasthan Royals       1             0            0   

      Qualifier 2  Semi Final  
0               0           0  
1               0           0  
2               0           0  
3               0           0  
4               0           0  
...           ...         ...  
1032            0           0  
1033            0           0  
1034            0           1  
1035            0           1  
1036            0           0  

[1037 rows x 8 columns]

In [182]:
new_data.columns = ["Home Team","Away Team","Winner","Final","Leaugh Match","Qualifier 1","Qualifier 2","Semi Final"]

In [183]:
new_data

Home Team              Away Team  \
0                  GUJARAT TITANS    CHENNAI SUPER KINGS   
1                    PUNJAB KINGS  KOLKATA KNIGHT RIDERS   
2            LUCKNOW SUPER GIANTS         DELHI CAPITALS   
3             SUNRISERS HYDERABAD       RAJASTHAN ROYALS   
4     ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
...                           ...                    ...   
1032  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
1033                 PUNJAB KINGS       RAJASTHAN ROYALS   
1034               DELHI CAPITALS       RAJASTHAN ROYALS   
1035          CHENNAI SUPER KINGS           PUNJAB KINGS   
1036          CHENNAI SUPER KINGS       RAJASTHAN ROYALS   

                            Winner  Final  Leaugh Match  Qualifier 1  \
0                  Gujarat Titans       0             1            0   
1                    Punjab Kings       0             1            0   
2            Lucknow Super Giants       0             1            0   
3                Rajasthan Royals       0             1            0   
4     Royal Challengers Bangalore       0             1            0   
...                            ...    ...           ...          ...   
1032               Mumbai Indians       0             1            0   
1033              Kings XI Punjab       0             1            0   
1034             Rajasthan Royals       0             0            0   
1035          Chennai Super Kings       0             0            0   
1036             Rajasthan Royals       1             0            0   

      Qualifier 2  Semi Final  
0               0           0  
1               0           0  
2               0           0  
3               0           0  
4               0           0  
...           ...         ...  
1032            0           0  
1033            0           0  
1034            0           1  
1035            0           1  
1036            0           0  

[1037 rows x 8 columns]

In [184]:
new_data["Home Team"] == new_data["Winner"]

0       False
1       False
2       False
3       False
4       False
        ...  
1032    False
1033    False
1034    False
1035    False
1036    False
Length: 1037, dtype: bool

In [185]:


df = new_data.applymap(lambda x: x.lower() if isinstance(x, str) else x)

In [186]:
df

Home Team              Away Team  \
0                  gujarat titans    chennai super kings   
1                    punjab kings  kolkata knight riders   
2            lucknow super giants         delhi capitals   
3             sunrisers hyderabad       rajasthan royals   
4     royal challengers bangalore         mumbai indians   
...                           ...                    ...   
1032  royal challengers bangalore         mumbai indians   
1033                 punjab kings       rajasthan royals   
1034               delhi capitals       rajasthan royals   
1035          chennai super kings           punjab kings   
1036          chennai super kings       rajasthan royals   

                            Winner  Final  Leaugh Match  Qualifier 1  \
0                  gujarat titans       0             1            0   
1                    punjab kings       0             1            0   
2            lucknow super giants       0             1            0   
3                rajasthan royals       0             1            0   
4     royal challengers bangalore       0             1            0   
...                            ...    ...           ...          ...   
1032               mumbai indians       0             1            0   
1033              kings xi punjab       0             1            0   
1034             rajasthan royals       0             0            0   
1035          chennai super kings       0             0            0   
1036             rajasthan royals       1             0            0   

      Qualifier 2  Semi Final  
0               0           0  
1               0           0  
2               0           0  
3               0           0  
4               0           0  
...           ...         ...  
1032            0           0  
1033            0           0  
1034            0           1  
1035            0           1  
1036            0           0  

[1037 rows x 8 columns]

In [187]:
df["Away Team"]

0         chennai super kings
1       kolkata knight riders
2              delhi capitals
3            rajasthan royals
4              mumbai indians
                ...          
1032           mumbai indians
1033         rajasthan royals
1034         rajasthan royals
1035             punjab kings
1036         rajasthan royals
Name: Away Team, Length: 1037, dtype: object

In [188]:
df["Winner"][3]

'rajasthan royals '

In [189]:
df["Away Team"][3]

'rajasthan royals'

In [190]:
arr  = np.array(df["Away Team"])

In [191]:
arr

array(['chennai super kings', 'kolkata knight riders', 'delhi capitals',
       ..., 'rajasthan royals', 'punjab kings', 'rajasthan royals'],
      dtype=object)

In [192]:
arr2 = np.array(df["Winner"])

In [193]:
arr2

array(['gujarat titans ', 'punjab kings ', 'lucknow super giants ', ...,
       'rajasthan royals ', 'chennai super kings ', 'rajasthan royals '],
      dtype=object)

In [194]:
np.where(arr == arr2)

(array([], dtype=int64),)

In [195]:
df['Home_Winner'] = (df['Winner'] == df['Home Team']).astype(int)

In [196]:
df.drop(columns=['Home_Winner'],axis=1,inplace=True)

In [197]:
df

Home Team              Away Team  \
0                  gujarat titans    chennai super kings   
1                    punjab kings  kolkata knight riders   
2            lucknow super giants         delhi capitals   
3             sunrisers hyderabad       rajasthan royals   
4     royal challengers bangalore         mumbai indians   
...                           ...                    ...   
1032  royal challengers bangalore         mumbai indians   
1033                 punjab kings       rajasthan royals   
1034               delhi capitals       rajasthan royals   
1035          chennai super kings           punjab kings   
1036          chennai super kings       rajasthan royals   

                            Winner  Final  Leaugh Match  Qualifier 1  \
0                  gujarat titans       0             1            0   
1                    punjab kings       0             1            0   
2            lucknow super giants       0             1            0   
3                rajasthan royals       0             1            0   
4     royal challengers bangalore       0             1            0   
...                            ...    ...           ...          ...   
1032               mumbai indians       0             1            0   
1033              kings xi punjab       0             1            0   
1034             rajasthan royals       0             0            0   
1035          chennai super kings       0             0            0   
1036             rajasthan royals       1             0            0   

      Qualifier 2  Semi Final  
0               0           0  
1               0           0  
2               0           0  
3               0           0  
4               0           0  
...           ...         ...  
1032            0           0  
1033            0           0  
1034            0           1  
1035            0           1  
1036            0           0  

[1037 rows x 8 columns]

In [198]:
import pandas as pd


df['Home_Winner'] = (df['Winner'].str.lower().str.strip() == df['Home Team'].str.lower().str.strip()).astype(int)



In [199]:
df

Home Team              Away Team  \
0                  gujarat titans    chennai super kings   
1                    punjab kings  kolkata knight riders   
2            lucknow super giants         delhi capitals   
3             sunrisers hyderabad       rajasthan royals   
4     royal challengers bangalore         mumbai indians   
...                           ...                    ...   
1032  royal challengers bangalore         mumbai indians   
1033                 punjab kings       rajasthan royals   
1034               delhi capitals       rajasthan royals   
1035          chennai super kings           punjab kings   
1036          chennai super kings       rajasthan royals   

                            Winner  Final  Leaugh Match  Qualifier 1  \
0                  gujarat titans       0             1            0   
1                    punjab kings       0             1            0   
2            lucknow super giants       0             1            0   
3                rajasthan royals       0             1            0   
4     royal challengers bangalore       0             1            0   
...                            ...    ...           ...          ...   
1032               mumbai indians       0             1            0   
1033              kings xi punjab       0             1            0   
1034             rajasthan royals       0             0            0   
1035          chennai super kings       0             0            0   
1036             rajasthan royals       1             0            0   

      Qualifier 2  Semi Final  Home_Winner  
0               0           0            1  
1               0           0            1  
2               0           0            1  
3               0           0            0  
4               0           0            1  
...           ...         ...          ...  
1032            0           0            0  
1033            0           0            0  
1034            0           1            0  
1035            0           1            1  
1036            0           0            0  

[1037 rows x 9 columns]

In [200]:
df.drop(columns=["Winner"],axis=1)

Home Team              Away Team  Final  Leaugh Match  \
0                  gujarat titans    chennai super kings      0             1   
1                    punjab kings  kolkata knight riders      0             1   
2            lucknow super giants         delhi capitals      0             1   
3             sunrisers hyderabad       rajasthan royals      0             1   
4     royal challengers bangalore         mumbai indians      0             1   
...                           ...                    ...    ...           ...   
1032  royal challengers bangalore         mumbai indians      0             1   
1033                 punjab kings       rajasthan royals      0             1   
1034               delhi capitals       rajasthan royals      0             0   
1035          chennai super kings           punjab kings      0             0   
1036          chennai super kings       rajasthan royals      1             0   

      Qualifier 1  Qualifier 2  Semi Final  Home_Winner  
0               0            0           0            1  
1               0            0           0            1  
2               0            0           0            1  
3               0            0           0            0  
4               0            0           0            1  
...           ...          ...         ...          ...  
1032            0            0           0            0  
1033            0            0           0            0  
1034            0            0           1            0  
1035            0            0           1            1  
1036            0            0           0            0  

[1037 rows x 8 columns]

In [201]:
new_df = df.drop(columns=["Winner"],axis=1)

In [202]:
new_df

Home Team              Away Team  Final  Leaugh Match  \
0                  gujarat titans    chennai super kings      0             1   
1                    punjab kings  kolkata knight riders      0             1   
2            lucknow super giants         delhi capitals      0             1   
3             sunrisers hyderabad       rajasthan royals      0             1   
4     royal challengers bangalore         mumbai indians      0             1   
...                           ...                    ...    ...           ...   
1032  royal challengers bangalore         mumbai indians      0             1   
1033                 punjab kings       rajasthan royals      0             1   
1034               delhi capitals       rajasthan royals      0             0   
1035          chennai super kings           punjab kings      0             0   
1036          chennai super kings       rajasthan royals      1             0   

      Qualifier 1  Qualifier 2  Semi Final  Home_Winner  
0               0            0           0            1  
1               0            0           0            1  
2               0            0           0            1  
3               0            0           0            0  
4               0            0           0            1  
...           ...          ...         ...          ...  
1032            0            0           0            0  
1033            0            0           0            0  
1034            0            0           1            0  
1035            0            0           1            1  
1036            0            0           0            0  

[1037 rows x 8 columns]

Home team 1 and away team 0

In [203]:
#perform encoding

df_encoded = pd.get_dummies(new_df, columns=['Home Team', 'Away Team'], prefix=['Home', 'Away'])

In [204]:
df_encoded

Final  Leaugh Match  Qualifier 1  Qualifier 2  Semi Final  Home_Winner  \
0         0             1            0            0           0            1   
1         0             1            0            0           0            1   
2         0             1            0            0           0            1   
3         0             1            0            0           0            0   
4         0             1            0            0           0            1   
...     ...           ...          ...          ...         ...          ...   
1032      0             1            0            0           0            0   
1033      0             1            0            0           0            0   
1034      0             0            0            0           1            0   
1035      0             0            0            0           1            1   
1036      1             0            0            0           0            0   

      Home_chennai super kings  Home_deccan chargers  Home_delhi capitals  \
0                            0                     0                    0   
1                            0                     0                    0   
2                            0                     0                    0   
3                            0                     0                    0   
4                            0                     0                    0   
...                        ...                   ...                  ...   
1032                         0                     0                    0   
1033                         0                     0                    0   
1034                         0                     0                    1   
1035                         1                     0                    0   
1036                         1                     0                    0   

      Home_gujarat lions  ...  Away_kochi tuskers kerala  \
0                      0  ...                          0   
1                      0  ...                          0   
2                      0  ...                          0   
3                      0  ...                          0   
4                      0  ...                          0   
...                  ...  ...                        ...   
1032                   0  ...                          0   
1033                   0  ...                          0   
1034                   0  ...                          0   
1035                   0  ...                          0   
1036                   0  ...                          0   

      Away_kolkata knight riders  Away_lucknow super giants  \
0                              0                          0   
1                              1                          0   
2                              0                          0   
3                              0                          0   
4                              0                          0   
...                          ...                        ...   
1032                           0                          0   
1033                           0                          0   
1034                           0                          0   
1035                           0                          0   
1036                           0                          0   

      Away_mumbai indians  Away_pune warriors  Away_punjab kings  \
0                       0                   0                  0   
1                       0                   0                  0   
2                       0                   0                  0   
3                       0                   0                  0   
4                       1                   0                  0   
...                   ...                 ...                ...   
1032                    1                   0                  0   
1033                    0                   0                  0   
1034                    0     

In [205]:
df_encoded.corr()

Final  Leaugh Match  Qualifier 1  \
Final                             1.000000     -0.511954    -0.014546   
Leaugh Match                     -0.511954      1.000000    -0.446815   
Qualifier 1                      -0.014546     -0.446815     1.000000   
Qualifier 2                      -0.014546     -0.446815    -0.012695   
Semi Final                       -0.009849     -0.302519    -0.008595   
Home_Winner                       0.039667     -0.032611    -0.046604   
Home_chennai super kings          0.187511     -0.133920     0.012279   
Home_deccan chargers             -0.025521      0.049849    -0.022274   
Home_delhi capitals              -0.047359     -0.008127     0.039084   
Home_gujarat lions               -0.016161     -0.034432     0.056216   
Home_gujarat titans               0.040989     -0.091056     0.117753   
Home_kochi tuskers kerala        -0.010643      0.020789    -0.009289   
Home_kolkata knight riders       -0.021409      0.063153    -0.039793   
Home_lucknow super giants        -0.016161     -0.034432    -0.014105   
Home_mumbai indians               0.001568     -0.024912     0.014213   
Home_pune warriors               -0.019443      0.037979    -0.016969   
Home_punjab kings                -0.045594      0.063153    -0.012191   
Home_rajasthan royals            -0.040998      0.051883    -0.035781   
Home_rising pune supergiant       0.047964     -0.003515    -0.013650   
Home_royal challengers bangalore -0.003008     -0.002795    -0.016482   
Home_sunrisers hyderabad         -0.038328      0.015238    -0.001685   
Away_chennai super kings          0.006575     -0.062599     0.133646   
Away_deccan chargers              0.016108     -0.017275    -0.021673   
Away_delhi capitals              -0.045594      0.063153    -0.039793   
Away_gujarat lions               -0.015103      0.029500    -0.013181   
Away_gujarat titans               0.107067     -0.034432    -0.014105   
Away_kochi tuskers kerala        -0.010643      0.020789    -0.009289   
Away_kolkata knight riders        0.019486     -0.075511     0.009334   
Away_lucknow super giants        -0.015103      0.029500    -0.013181   
Away_mumbai indians               0.019926     -0.015078     0.009692   
Away_pune warriors               -0.019443      0.037979    -0.016969   
Away_punjab kings                -0.022036      0.064216    -0.040181   
Away_rajasthan royals             0.003184     -0.002395    -0.011890   
Away_rising pune supergiant      -0.015640     -0.003515     0.058941   
Away_royal challengers bangalore -0.021409      0.011342    -0.012191   
Away_sunrisers hyderabad          0.017893     -0.000564    -0.033234   

                                  Qualifier 2  Semi Final  Home_Winner  \
Final                               -0.014546   -0.009849     0.039667   
Leaugh Match                        -0.446815   -0.302519    -0.032611   
Qualifier 1                         -0.012695   -0.008595    -0.046604   
Qualifier 2                          1.000000   -0.008595     0.040789   
Semi Final                          -0.008595    1.000000     0.009866   
Home_Winner                          0.040789    0.009866     1.000000   
Home_chennai super kings             0.039084    0.050661     0.176755   
Home_deccan chargers                -0.022274   -0.015080    -0.040878   
Home_delhi capitals                  0.012279    0.050661    -0.190135   
Home_gujarat lions                   0.056216   -0.009550    -0.031146   
Home_gujarat titans                  0.051389   -0.010139     0.061859   
Home_kochi tuskers kerala           -0.009289   -0.006289    -0.001214   
Home_kolkata knight riders          -0.039793   -0.026942     0.073542   
Home_lucknow super giants           -0.014105   -0.009550     0.000411   
Home_mumbai indians                  0.041506   -0.027336     0.101456   
Home_pune warriors                  -0.016969   -0.011489    -0.053152   
Home_punjab kings                   -0.012191   -0.026942    -0.267085   
Hom

In [206]:
#train ,test data

from sklearn.model_selection import train_test_split

In [207]:
X = df_encoded.drop(columns=['Home_Winner'] ,axis=1)

In [208]:
X

Final  Leaugh Match  Qualifier 1  Qualifier 2  Semi Final  \
0         0             1            0            0           0   
1         0             1            0            0           0   
2         0             1            0            0           0   
3         0             1            0            0           0   
4         0             1            0            0           0   
...     ...           ...          ...          ...         ...   
1032      0             1            0            0           0   
1033      0             1            0            0           0   
1034      0             0            0            0           1   
1035      0             0            0            0           1   
1036      1             0            0            0           0   

      Home_chennai super kings  Home_deccan chargers  Home_delhi capitals  \
0                            0                     0                    0   
1                            0                     0                    0   
2                            0                     0                    0   
3                            0                     0                    0   
4                            0                     0                    0   
...                        ...                   ...                  ...   
1032                         0                     0                    0   
1033                         0                     0                    0   
1034                         0                     0                    1   
1035                         1                     0                    0   
1036                         1                     0                    0   

      Home_gujarat lions  Home_gujarat titans  ...  Away_kochi tuskers kerala  \
0                      0                    1  ...                          0   
1                      0                    0  ...                          0   
2                      0                    0  ...                          0   
3                      0                    0  ...                          0   
4                      0                    0  ...                          0   
...                  ...                  ...  ...                        ...   
1032                   0                    0  ...                          0   
1033                   0                    0  ...                          0   
1034                   0                    0  ...                          0   
1035                   0                    0  ...                          0   
1036                   0                    0  ...                          0   

      Away_kolkata knight riders  Away_lucknow super giants  \
0                              0                          0   
1                              1                          0   
2                              0                          0   
3                              0                          0   
4                              0                          0   
...                          ...                        ...   
1032                           0                          0   
1033                           0                          0   
1034                           0                          0   
1035                           0                          0   
1036                           0                          0   

      Away_mumbai indians  Away_pune warriors  Away_punjab kings  \
0                       0                   0                  0   
1                       0                   0                  0   
2                       0                   0                  0   
3                       0                   0                  0   
4                       1                   0                  0   
...                   ...                 ...                ...   
1032                    1                   0                  0   
10

In [209]:

y = df_encoded["Home_Winner"]

In [210]:
y

0       1
1       1
2       1
3       0
4       1
       ..
1032    0
1033    0
1034    0
1035    1
1036    0
Name: Home_Winner, Length: 1037, dtype: int64

In [211]:
train_x , test_x,train_y,test_y = train_test_split(X,y,test_size=0.25,random_state=42)


In [212]:
class_priors = np.bincount(train_y) / len(train_y)

In [213]:
#model selection
#model creation
from sklearn.naive_bayes import MultinomialNB

In [214]:
model = MultinomialNB()


In [215]:
model.fit(train_x,train_y)

MultinomialNB()

In [216]:
y_pred = model.predict(test_x)

In [217]:
#check accurecy 

from sklearn.metrics import accuracy_score,classification_report,f1_score

In [218]:
accuracy_score = accuracy_score(test_y,y_pred)
print(f"{accuracy_score * 100:.2f}%")

61.15%


In [219]:
from sklearn.ensemble import RandomForestClassifier

In [220]:
r_model = RandomForestClassifier(max_depth=20)

In [221]:
r_model.fit(train_x,train_y)


RandomForestClassifier(max_depth=20)

In [222]:
ypred = r_model.predict(test_x)

In [225]:
from sklearn.metrics import accuracy_score
accuracy_score(test_y,ypred)

0.5846153846153846

In [227]:
from sklearn.tree import DecisionTreeClassifier

In [228]:
D_model = DecisionTreeClassifier()

In [229]:
D_model.fit(train_x,train_y)


DecisionTreeClassifier()

In [230]:
ypred = D_model.predict(test_x)

In [231]:
accuracy_score(test_y,ypred)

0.573076923076923

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc_model  = SVC(C=1)

In [ ]:
svc_model.fit(train_x, train_y)

SVC(C=1)

In [ ]:
ypred = svc_model.predict(test_x)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(test_y,ypred)

0.573076923076923

In [ ]:
test_x


Final  Leaugh Match  Qualifier 1  Qualifier 2  Semi Final  \
622      0             1            0            0           0   
109      0             1            0            0           0   
649      0             1            0            0           0   
458      0             1            0            0           0   
541      0             1            0            0           0   
..     ...           ...          ...          ...         ...   
516      0             1            0            0           0   
65       0             1            0            0           0   
355      0             1            0            0           0   
873      0             1            0            0           0   
254      0             1            0            0           0   

     Home_chennai super kings  Home_deccan chargers  Home_delhi capitals  \
622                         1                     0                    0   
109                         0                     0                    0   
649                         0                     0                    0   
458                         0                     0                    0   
541                         0                     0                    0   
..                        ...                   ...                  ...   
516                         1                     0                    0   
65                          0                     0                    0   
355                         0                     0                    0   
873                         0                     1                    0   
254                         0                     0                    0   

     Home_gujarat lions  Home_gujarat titans  ...  Away_kochi tuskers kerala  \
622                   0                    0  ...                          0   
109                   0                    0  ...                          0   
649                   0                    0  ...                          0   
458                   1                    0  ...                          0   
541                   0                    0  ...                          0   
..                  ...                  ...  ...                        ...   
516                   0                    0  ...                          0   
65                    0                    0  ...                          0   
355                   0                    0  ...                          0   
873                   0                    0  ...                          0   
254                   0                    0  ...                          0   

     Away_kolkata knight riders  Away_lucknow super giants  \
622                           0                          0   
109                           0                          0   
649                           0                          0   
458                           0                          0   
541                           0                          0   
..                          ...                        ...   
516                           0                          0   
65                            0                          0   
355                           0                          0   
873                           0                          0   
254                           0                          0   

     Away_mumbai indians  Away_pune warriors  Away_punjab kings  \
622                    0                   0                  0   
109                    0                   0                  0   
649                    0                   0                  0   
458                    0                   0                  0   
541                    0                   0                  0   
..                   ...                 ...                ...   
516                    0                   0                  0   
65                     0                   0             

In [250]:
test_y

622    0
109    0
649    1
458    1
541    0
      ..
516    1
65     0
355    0
873    1
254    1
Name: Home_Winner, Length: 260, dtype: int64

In [247]:
pred_data = [0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]

In [249]:
model.predict([pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([1])

In [ ]:

data

IPL Edition                                      Match Details  \
0            2023   GUJARAT TITANS vs CHENNAI SUPER KINGS, 1st Match   
1            2023   PUNJAB KINGS vs KOLKATA KNIGHT RIDERS, 2nd Match   
2            2023  LUCKNOW SUPER GIANTS vs DELHI CAPITALS, 3rd Match   
3            2023  SUNRISERS HYDERABAD vs RAJASTHAN ROYALS, 4th M...   
4            2023  ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...   
...           ...                                                ...   
1032         2008  ROYAL CHALLENGERS BANGALORE vs MUMBAI INDIANS,...   
1033         2008       PUNJAB KINGS vs RAJASTHAN ROYALS, 56th match   
1034         2008  DELHI CAPITALS vs RAJASTHAN ROYALS, 1st Semi-F...   
1035         2008  CHENNAI SUPER KINGS vs PUNJAB KINGS, 2nd Semi-...   
1036         2008     CHENNAI SUPER KINGS vs RAJASTHAN ROYALS, Final   

                           Team 1                 Team 2  \
0                  GUJARAT TITANS    CHENNAI SUPER KINGS   
1                    PUNJAB KINGS  KOLKATA KNIGHT RIDERS   
2            LUCKNOW SUPER GIANTS         DELHI CAPITALS   
3             SUNRISERS HYDERABAD       RAJASTHAN ROYALS   
4     ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
...                           ...                    ...   
1032  ROYAL CHALLENGERS BANGALORE         MUMBAI INDIANS   
1033                 PUNJAB KINGS       RAJASTHAN ROYALS   
1034               DELHI CAPITALS       RAJASTHAN ROYALS   
1035          CHENNAI SUPER KINGS           PUNJAB KINGS   
1036          CHENNAI SUPER KINGS       RAJASTHAN ROYALS   

                            Winner  
0                  Gujarat Titans   
1                    Punjab Kings   
2            Lucknow Super Giants   
3                Rajasthan Royals   
4     Royal Challengers Bangalore   
...                            ...  
1032               Mumbai Indians   
1033              Kings XI Punjab   
1034             Rajasthan Royals   
1035          Chennai Super Kings   
1036             Rajasthan Royals   

[1037 rows x 5 columns]

In [ ]:
df_encoded.columns.value_counts

<bound method IndexOpsMixin.value_counts of Index(['Final', 'Leaugh Match', 'Qualifier 1', 'Qualifier 2', 'Semi Final',
       'Home_Winner', 'Home_chennai super kings', 'Home_deccan chargers',
       'Home_delhi capitals', 'Home_gujarat lions', 'Home_gujarat titans',
       'Home_kochi tuskers kerala', 'Home_kolkata knight riders',
       'Home_lucknow super giants', 'Home_mumbai indians',
       'Home_pune warriors', 'Home_punjab kings', 'Home_rajasthan royals',
       'Home_rising pune supergiant', 'Home_royal challengers bangalore',
       'Home_sunrisers hyderabad', 'Away_chennai super kings',
       'Away_deccan chargers', 'Away_delhi capitals', 'Away_gujarat lions',
       'Away_gujarat titans', 'Away_kochi tuskers kerala',
       'Away_kolkata knight riders', 'Away_lucknow super giants',
       'Away_mumbai indians', 'Away_pune warriors', 'Away_punjab kings',
       'Away_rajasthan royals', 'Away_rising pune supergiant',
       'Away_royal challengers bangalore', 'Away_sunriser

In [ ]:
prediction = [0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,]

In [ ]:
model.predict([prediction])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([1])

In [ ]:
r_model.predict([prediction])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])

In [232]:
D_model.predict([prediction])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [233]:
svc_model.predict([prediction])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1])

In [234]:
#linear model 

from sklearn.linear_model import Perceptron

In [235]:
p_model = Perceptron()


In [236]:
p_model.fit(train_x,train_y)

Perceptron()

In [237]:
pred = p_model.predict(test_x)

In [238]:
accuracy_score(test_y,ypred)

0.573076923076923

In [246]:
p_model.predict([prediction])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  warnings.warn(


array([1])

In [239]:
#KNN model

from sklearn.neighbors import KNeighborsClassifier

In [240]:
k_model = KNeighborsClassifier(n_neighbors=7)


In [241]:
k_model.fit(train_x,train_y)

KNeighborsClassifier(n_neighbors=7)

In [242]:
ypred = k_model.predict(test_x)

In [244]:
accuracy_score(test_y,ypred)

0.6076923076923076

In [245]:
k_model.predict([prediction])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0])

In [251]:
clr = classification_report(test_y,ypred)

In [252]:
print(clr)

              precision    recall  f1-score   support

           0       0.70      0.64      0.67       160
           1       0.49      0.55      0.52       100

    accuracy                           0.61       260
   macro avg       0.59      0.60      0.59       260
weighted avg       0.62      0.61      0.61       260



In [253]:
D_model.predict([pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [254]:
r_model.predict([pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])

In [255]:
k_model.predict([pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1])

In [256]:
p_model.predict([pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  warnings.warn(


array([1])

In [257]:
svc_model.predict([pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1])

In [258]:
pred_data


[0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1]

In [259]:
new_pred_data = [0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

In [260]:
model.predict([new_pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([0])

In [261]:
svc_model.predict([new_pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0])

In [262]:
D_model.predict([new_pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

In [263]:
r_model.predict([new_pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])

In [264]:
k_model.predict([new_pred_data])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0])