In [1]:
import numpy as np

In [2]:
import pandas as pd 


In [3]:
from sklearn.tree import DecisionTreeClassifier

In [4]:
df  = pd.read_csv("Movie Interests.csv")

In [5]:
df

Age  Gender   Interest
0     8       1  Animation
1    11       1  Animation
2    12       1  Animation
3    16       1     Action
4    18       1     Action
5    19       1     Action
6    23       1      Drama
7    26       1      Drama
8    27       1      Drama
9     7       0  Animation
10    9       0  Animation
11   10       0  Animation
12   26       0     Action
13   27       0     Action
14   30       0     Action
15   31       0      Drama
16   34       0      Drama
17   35       0      Drama

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Age       18 non-null     int64 
 1   Gender    18 non-null     int64 
 2   Interest  18 non-null     object
dtypes: int64(2), object(1)
memory usage: 564.0+ bytes


In [7]:
df.describe()

Age     Gender
count  18.000000  18.000000
mean   20.500000   0.500000
std     9.444887   0.514496
min     7.000000   0.000000
25%    11.250000   0.000000
50%    21.000000   0.500000
75%    27.000000   1.000000
max    35.000000   1.000000

In [8]:
df.corr()

/tmp/ipykernel_20563/1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


Age    Gender
Age     1.000000 -0.296578
Gender -0.296578  1.000000

In [11]:
X = df.drop(columns= ['Interest'], axis=1)
X

Age  Gender
0     8       1
1    11       1
2    12       1
3    16       1
4    18       1
5    19       1
6    23       1
7    26       1
8    27       1
9     7       0
10    9       0
11   10       0
12   26       0
13   27       0
14   30       0
15   31       0
16   34       0
17   35       0

In [12]:
y = df["Interest"]
y 

0     Animation
1     Animation
2     Animation
3        Action
4        Action
5        Action
6         Drama
7         Drama
8         Drama
9     Animation
10    Animation
11    Animation
12       Action
13       Action
14       Action
15        Drama
16        Drama
17        Drama
Name: Interest, dtype: object

In [14]:
model = DecisionTreeClassifier()


In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train , X_test ,y_train ,y_test = train_test_split(X,y,test_size=0.25,random_state=42)


In [17]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [21]:
y_pred = model.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score


In [22]:
acc  = accuracy_score(y_test,y_pred)
acc

1.0

In [23]:

print(f"Accuracy: {acc * 100:.2f}%")

Accuracy: 100.00%


In [25]:
X_test

Age  Gender
0    8       1
1   11       1
8   27       1
5   19       1
3   16       1

In [26]:
#make prediction 


model.predict([[15,0]])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array(['Animation'], dtype=object)

In [27]:
model.predict([[9,1],[33,0]])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array(['Animation', 'Drama'], dtype=object)

In [28]:
model.predict([[33,1]])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array(['Drama'], dtype=object)

In [29]:
model.predict([[18,1]])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array(['Action'], dtype=object)

IRIS DATA SET 

In [30]:
from sklearn.datasets import load_iris

In [32]:
iris = load_iris()
X = iris.data

In [33]:
y = iris.target

In [41]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [35]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [37]:
train_x ,test_x , train_y, test_y = train_test_split(X,y,test_size=0.25,random_state=42)

In [45]:
new_model = DecisionTreeClassifier(random_state=42)


In [47]:
new_model.fit(train_x,train_y)

DecisionTreeClassifier(random_state=42)

In [50]:
y_pred =new_model.predict(test_x)

In [51]:
acc = accuracy_score(test_y,y_pred)

In [52]:
acc

1.0

In [53]:
sample_input = np.array([[5.1, 3.5, 1.4, 0.2]])

In [54]:
new_model.predict(sample_input)

array([0])

In [55]:
np.unique(y)

array([0, 1, 2])

In [56]:
df = pd.DataFrame(X,y)

In [57]:
df

0    1    2    3
0   5.1  3.5  1.4  0.2
0   4.9  3.0  1.4  0.2
0   4.7  3.2  1.3  0.2
0   4.6  3.1  1.5  0.2
0   5.0  3.6  1.4  0.2
..  ...  ...  ...  ...
2   6.7  3.0  5.2  2.3
2   6.3  2.5  5.0  1.9
2   6.5  3.0  5.2  2.0
2   6.2  3.4  5.4  2.3
2   5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [58]:
from sklearn.metrics import classification_report

In [59]:
clr  = classification_report(test_y,y_pred)
clr

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        15\n           1       1.00      1.00      1.00        11\n           2       1.00      1.00      1.00        12\n\n    accuracy                           1.00        38\n   macro avg       1.00      1.00      1.00        38\nweighted avg       1.00      1.00      1.00        38\n'

In [60]:
print(clr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [62]:
df.corr()

0         1         2         3
0  1.000000 -0.117570  0.871754  0.817941
1 -0.117570  1.000000 -0.428440 -0.366126
2  0.871754 -0.428440  1.000000  0.962865
3  0.817941 -0.366126  0.962865  1.000000