In [2]:
import numpy as np

In [3]:
import pandas as pd

import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv('california_housing_train.csv')

In [8]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [9]:
df.columns.tolist()

['longitude',
 'latitude',
 'housing_median_age',
 'total_rooms',
 'total_bedrooms',
 'population',
 'households',
 'median_income',
 'median_house_value']

In [10]:
df.info

<bound method DataFrame.info of        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB


In [12]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [13]:
df.corr()

longitude  latitude  housing_median_age  total_rooms  \
longitude            1.000000 -0.925208           -0.114250     0.047010   
latitude            -0.925208  1.000000            0.016454    -0.038773   
housing_median_age  -0.114250  0.016454            1.000000    -0.360984   
total_rooms          0.047010 -0.038773           -0.360984     1.000000   
total_bedrooms       0.071802 -0.069373           -0.320434     0.928403   
population           0.101674 -0.111261           -0.295890     0.860170   
households           0.059628 -0.074902           -0.302754     0.919018   
median_income       -0.015485 -0.080303           -0.115932     0.195383   
median_house_value  -0.044982 -0.144917            0.106758     0.130991   

                    total_bedrooms  population  households  median_income  \
longitude                 0.071802    0.101674    0.059628      -0.015485   
latitude                 -0.069373   -0.111261   -0.074902      -0.080303   
housing_median_age       -0.320434   -0.295890   -0.302754      -0.115932   
total_rooms               0.928403    0.860170    0.919018       0.195383   
total_bedrooms            1.000000    0.881169    0.980920      -0.013495   
population                0.881169    1.000000    0.909247      -0.000638   
households                0.980920    0.909247    1.000000       0.007644   
median_income            -0.013495   -0.000638    0.007644       1.000000   
median_house_value        0.045783   -0.027850    0.061031       0.691871   

                    median_house_value  
longitude                    -0.044982  
latitude                     -0.144917  
housing_median_age            0.106758  
total_rooms                   0.130991  
total_bedrooms                0.045783  
population                   -0.027850  
households                    0.061031  
median_income                 0.691871  
median_house_value            1.000000

In [14]:
y  = df['median_house_value']

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
y =  df['median_house_value']

In [18]:
X = df.drop(['median_house_value'],axis=1)

In [20]:
X


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  
0          1015.0       472.0         1.4936  
1          1129.0       463.0         1.8200  
2           333.0       117.0         1.6509  
3           515.0       226.0         3.1917  
4           624.0       262.0         1.9250  
...           ...         ...            ...  
16995       907.0       369.0         2.3571  
16996      1194.0       465.0         2.5179  
16997      1244.0       456.0         3.0313  
16998      1298.0       478.0         1.9797  
16999       806.0       270.0         3.0147  

[17000 rows x 8 columns]

In [21]:
X.shape

(17000, 8)

In [22]:
y.shape

(17000,)

In [23]:
#spilt training data and test data  import the modules 

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score


In [24]:
#train test data

train_x ,test_x ,train_y ,test_y = train_test_split(X,y,test_size=0.25,random_state=42)


In [25]:
print(train_x.shape)
print(test_x.shape)
print(train_y.shape)
print(test_y.shape)


(12750, 8)
(4250, 8)
(12750,)
(4250,)


plot the train data


In [26]:
#Create the model to train 

model = LinearRegression()



In [32]:
model.fit(train_x,train_y)


LinearRegression()

In [35]:
#give the test data to predict 

y_pred = model.predict(test_x)

In [38]:
#Calulate the errors 
#MAE,MSE,RMSE,r2_score,ROOT R2_sore 

MAE = mean_absolute_error(test_y,y_pred)
MAE



50476.546304319214

In [39]:
MSE = mean_squared_error(test_y,y_pred)

MSE

4711376982.39137

In [40]:
from math import sqrt

RMSE = sqrt(MSE)

In [43]:
RMSE

68639.47102353987

In [44]:
#r2_score 

r2_score = r2_score(test_y,y_pred)

r2_score

0.6567982035723627

In [46]:
# square r2_score
#calculat the r2 square model
# 1-((1-score)*(1-N))/(N-p-1)
#N no of sample
#p is depantant varibale count

N = len(test_y)
p = 1
ar2 = 1-((1-r2_score)*(1-N))/(N-p-1)

In [47]:
ar2

1.343282587810977

In [53]:
#give some sample to predict in unseen data 

predict =pd.DataFrame({
    "longitude":[-114.470000],
    "latitude":[39.690000],
    "housing_median_age":[49.000000],
    "total_rooms":[7950.000000],
    "total_bedrooms":[174.000000],
    "population":[1129.000000],
    "households":[1.493600],
    "median_income":[1.820000]

})

In [55]:
model.predict(predict)

array([-349254.58933226])

In [56]:
#create model only have the feauter income and rooms 

df = pd.read_csv('california_housing_train.csv')

In [57]:
X = df[["total_rooms","total_bedrooms","median_income"]]



In [58]:
X

total_rooms  total_bedrooms  median_income
0           5612.0          1283.0         1.4936
1           7650.0          1901.0         1.8200
2            720.0           174.0         1.6509
3           1501.0           337.0         3.1917
4           1454.0           326.0         1.9250
...            ...             ...            ...
16995       2217.0           394.0         2.3571
16996       2349.0           528.0         2.5179
16997       2677.0           531.0         3.0313
16998       2672.0           552.0         1.9797
16999       1820.0           300.0         3.0147

[17000 rows x 3 columns]

In [60]:
y = df["median_house_value"]

In [61]:
#train_data

x_train ,x_test , y_train ,y_test = train_test_split(X,y,test_size=0.25,random_state=42)



In [80]:
y_train.shape

(12750,)

In [62]:
model  = LinearRegression()

In [69]:
model.fit(x_train,y_train)


LinearRegression()

In [70]:
ypred  = model.predict(x_test)

In [71]:
#calulate errors

mae = mean_absolute_error(y_test,ypred)
mae

59810.72947448997

In [72]:
mse  = mean_squared_error(y_test,ypred)
mse

6522779487.527128

In [68]:
rmse  = sqrt(mse)
rmse

68639.47102353987

In [78]:
y_test.shape

(4250,)

In [82]:
from sklearn.metrics import  r2_score

In [83]:
score  = r2_score(y_test,ypred)

In [84]:
score

0.5248459959397296

In [85]:
#average model 


In [87]:
# give the unseen seen data to predict 

In [89]:
model.predict([[5612.0	,1283.0	,1.4936]])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([119913.03132512])

In [90]:
model.predict([[6000.0,1245.0,2.3455]])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([143257.58690962])

In [102]:
# r square r2 score

In [97]:
# square r2_score
#calculat the r2 square model
# 1-((1-score)*(1-N))/(N-p-1)
#N no of sample
#p is depantant varibale count
from sklearn.metrics import r2_score

N = len(y_test)
p = 1
ar = 1-((1-score)*(1-N))/(N-p-1)
ar

1.4752658576393807

In [98]:
#save the model 

import pickle

path = "/home/saaho/Mechine_learnig/Machine_basics/linearRecogration_model/House_price_model/house_model.pkl"




In [100]:
with open(path,'wb') as file:
    pickle.dump(model,file)


In [101]:
#load model

with open(path,'rb') as file:
    load_model = pickle.load(file)
    

In [103]:
load_model.predict([[6000.0,1245.0,2.3455]])

/home/saaho/.local/lib/python3.11/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([143257.58690962])